### ISSUE TITLE
Update ?

### ISSUE THREAD

**Issue by bnff** [Foohx/DofusWeb-API#1]
Bonjour,

Après plus de 4 ans le script ne fonctionne plus je suppose que les url et paramètre on du changer ...
Possible d'avoir une update ou une reprise ... je vais try de mon coté.

cdt

**Comment by Foohx** [comment]
Je peux éventuellement voir ce que je peux faire 👍

**Comment by bnff** [comment]
Je viens de  test, cela marche enfin peut être pas tout mais la connexion fonctionne !

Je n'ai par contre aucune erreur si je ne suis pas connecté par exemple étant très limité en PHP
